### ISSUE TITLE
After reinitializing a cache from localStorage, info().size returns 0

### ISSUE THREAD

**Issue by sloops77** [jmdobry/CacheFactory#1]
if the cache needs to reinitialize from local storage, lets say 10 items: `cache.keys().length === 10` but `cache.info().size === 0`. During `setStorageMode` the `$$lruHeap` should be initialized, right?

**Comment by jmdobry** [comment]
Yes, this is a bug.

**Comment by sloops77** [comment]
i can fix it tomorrow if you like and send a pr

**Comment by jmdobry** [comment]
This is somewhat of an involved fix, because right now the `$$exiresHeap` isn't getting initialized either. I'm planning to fix it on Saturday when I finally have internet at my house.

**Comment by sloops77** [comment]
ok
