### ISSUE TITLE
touch doesn't honor key-specific options

### ISSUE THREAD

**Issue by kwv** [jmdobry/CacheFactory#10]
I hoped to leverage CacheFactory's maxAge to expire items at different intervals. (e.g. session data expires at 12h, but an authentication is locally expunged at 5 minutes idle).

```
      var options = {
        deleteOnExpire: 'aggressive',
        cacheFlushInterval: CACHE_DURATION,
        storageMode: 'localStorage',
        onExpire: function(){$log.warn("local session expiring"); logout();} 
      };
      CacheFactory.createCache(SESSION_CACHE, options);
```

```
CacheFactory.get(SESSION_CACHE).put(CURRENT_USER_KEY,
              username.toUpperCase(),
              {maxAge: AUTH_DURATION});
```

I expected that `CacheFactory.get(SESSION_CACHE).touch(CURRENT_USER_KEY);` options specified on the initial PUT would be preserved.   

https://github.com/kwv/CacheFactory/commit/ef280251cea8c5977152d2dd2d237b5edc6c08e8 adds options object to the API, however I wasn't certain of the usecase behind https://github.com/jmdobry/CacheFactory/blob/master/src/index.js#L819

**Comment by jmdobry** [comment]
Closed by #11
