### ISSUE TITLE
Allow async implementation of cache interface

### ISSUE THREAD

**Issue by jrencz** [jmdobry/CacheFactory#6]
I tried to connect `angular-cache` with [ocombe/angular-localForage](https://github.com/ocombe/angular-localForage) (in general - `CacheFactory` and [mozilla/localForage](https://github.com/mozilla/localForage)) but it turns out that async storge implementation is not supported by `CacheFactory`. For example [index.js#L417-L420](https://github.com/jmdobry/CacheFactory/blob/89de7d121d1450442af55ba2975ce235d89496f3/src/index.js#L417-L420):

``` js
$$storage().removeItem(this.$$prefix + '.data.' + key);
var keysJson = $$storage().getItem(this.$$prefix + '.keys');
var keys = keysJson ? utils.fromJson(keysJson) : [];
var index = keys.indexOf(key);
```

this clearly does not allow `removeItem` and `getItem` to return promises.

@jmdobry are you interested in implementing async storage in `CacheFactory`? Do you see any obvious cons for this idea?

**Comment by jmdobry** [comment]
See https://github.com/jmdobry/angular-cache/pull/146#issuecomment-72510034 and https://github.com/jmdobry/angular-cache/issues/108#issuecomment-45746483

I recommend [js-data](http://www.js-data.io) & [js-data-localforage](https://github.com/js-data/js-data-localforage) instead.

**Comment by jrencz** [comment]
Ok
